#!/bin/sh
# BC Inventory — point the API at ApsaraDB RDS.  Runs on the backend server (172.28.92.57),
# AFTER migrate-to-apsaradb.sh verify has reported every object class identical.
#
# This backend reads its database settings from exactly one place: the compose project .env
# beside this script, substituted into ConnectionStrings__Db in docker-compose.yml. There is
# no env_file and no second .env, so there is no precedence question to resolve here.
#
# The script writes its own rollback with the CURRENT values baked in as literals, so the
# reverse move never depends on a backup file that may have been overwritten afterwards.
#
# Usage:  RDS_HOST=... RDS_PORT=5432 RDS_DB=bcinventory RDS_USER=... RDS_PW=... ./cutover-to-apsaradb.sh
set -e
cd "$(dirname "$0")"

[ -f .env ] || { echo "FATAL: .env not found in $(pwd)"; exit 1; }

for v in RDS_HOST RDS_PORT RDS_DB RDS_USER RDS_PW; do
  eval "val=\$$v"
  case "$val" in
    ""|CHANGE_ME|"<"*|*xxxxxxxx*) echo "FATAL: $v is unset or a placeholder ('$val')"; exit 1 ;;
  esac
done

# Rewrite a key in place with awk, not sed: a password containing & | or \ carries meaning
# in a sed replacement and would be silently corrupted in the file the application reads.
# Values travel through the environment rather than awk -v: -v applies escape processing,
# so a password containing a backslash would arrive with the backslash silently removed.
set_env() {
  k="$2" v="$3" awk '
    $0 ~ "^" ENVIRON["k"] "=" { print ENVIRON["k"] "=" ENVIRON["v"]; seen=1; next }
    { print }
    END { if (!seen) print ENVIRON["k"] "=" ENVIRON["v"] }
  ' "$1" > "$1.new" && mv "$1.new" "$1"
}
# Escape a value for embedding inside a single-quoted shell literal.
q() { printf '%s' "$1" | sed "s/'/'\\\\''/g"; }

get() { grep -E "^$1=" .env | head -1 | cut -d= -f2-; }
OLD_HOST=$(get DB_HOST);  OLD_PORT=$(get DB_PORT);  OLD_PW=$(get DB_PASSWORD)
OLD_USER=$(get DB_USER);  OLD_DB=$(get DB_NAME)
# DB_USER/DB_NAME were added with this migration; an older .env predates them.
[ -n "$OLD_USER" ] || OLD_USER=bcapp
[ -n "$OLD_DB" ]   || OLD_DB=bcinventory
[ -n "$OLD_HOST" ] || { echo "FATAL: DB_HOST not set in .env — refusing to guess a rollback target."; exit 1; }

echo "  from: $OLD_USER@$OLD_HOST:$OLD_PORT/$OLD_DB"
echo "    to: $RDS_USER@$RDS_HOST:$RDS_PORT/$RDS_DB"

cat > rollback-to-selfmanaged.sh <<ROLLBACK
#!/bin/sh
# Generated by cutover-to-apsaradb.sh. The values below are literals on purpose: a rollback
# must not depend on a backup copy of .env, which may have been overwritten after the
# cutover was applied — restoring from it would point back at the NEW database.
set -e
cd "\$(dirname "\$0")"
set_env() {
  k="\$2" v="\$3" awk '
    \$0 ~ "^" ENVIRON["k"] "=" { print ENVIRON["k"] "=" ENVIRON["v"]; seen=1; next }
    { print }
    END { if (!seen) print ENVIRON["k"] "=" ENVIRON["v"] }
  ' "\$1" > "\$1.new" && mv "\$1.new" "\$1"
}
set_env .env DB_HOST '$(q "$OLD_HOST")'
set_env .env DB_PORT '$(q "$OLD_PORT")'
set_env .env DB_USER '$(q "$OLD_USER")'
set_env .env DB_NAME '$(q "$OLD_DB")'
set_env .env DB_PASSWORD '$(q "$OLD_PW")'
docker compose -f docker-compose.yml up -d --force-recreate api
docker inspect bc-inventory-api --format '{{range .Config.Env}}{{println .}}{{end}}' \\
  | grep '^ConnectionStrings__Db=' | sed 's/Password=[^;]*/Password=***/'
echo "ROLLED BACK to $OLD_HOST:$OLD_PORT"
ROLLBACK
chmod +x rollback-to-selfmanaged.sh
echo "wrote rollback-to-selfmanaged.sh (rollback target: $OLD_USER@$OLD_HOST:$OLD_PORT/$OLD_DB)"

set_env .env DB_HOST     "$RDS_HOST"
set_env .env DB_PORT     "$RDS_PORT"
set_env .env DB_USER     "$RDS_USER"
set_env .env DB_NAME     "$RDS_DB"
set_env .env DB_PASSWORD "$RDS_PW"

# up -d --force-recreate, never start/restart: those reuse the environment baked into the
# container when it was created, so the API would keep using the old database while .env
# claims otherwise — a cutover that appears to work and has not taken effect.
docker compose -f docker-compose.yml up -d --force-recreate api

echo "GATE: what the container actually received"
docker inspect bc-inventory-api --format '{{range .Config.Env}}{{println .}}{{end}}' \
  | grep '^ConnectionStrings__Db=' | sed 's/Password=[^;]*/Password=***/'
echo "Check the host, port, database and username above, then confirm the password reached"
echo "the container intact: Compose treats # as a comment only after whitespace, and a \$ in"
echo "an unquoted value is interpolated away. Either failure surfaces only as an opaque"
echo "authentication error."

sleep 8
docker logs --tail 30 bc-inventory-api
echo
echo "Next: log in, open Reports and the audit log, and confirm the figures match what"
echo "migrate-to-apsaradb.sh verify recorded. This app seeds accounts only into an empty"
echo "user table, so the user count must be unchanged — check it rather than assuming."
